name: default

kind: pipeline
type: docker

workspace:
  path: /drone/trshcmpctr

steps:
- name: install
  image: node:gallium
  commands:
    - node common/scripts/install-run-rush.js install

- name: inject_secrets
  image: node:gallium
  environment:
    DISCORD_CLIENT_ID:
      from_secret: discord_client_id
    DISCORD_CLIENT_SECRET:
      from_secret: discord_client_secret
    DISCORD_GUILD_ID:
      from_secret: discord_guild_id
    DISCORD_SESSION_SECRET:
      from_secret: discord_session_secret
  commands:
    - (cd discord && ./client_config_ci.sh)

- name: lint
  image: node:gallium
  commands:
    - node common/scripts/install-run-rush.js lint
  depends_on:
    - install
    - inject_secrets

- name: lint:md
  image: node:gallium
  commands:
    - node common/scripts/install-run-rush.js lint:md
  depends_on:
    - install

- name: test
  image: node:gallium
  commands:
    - node common/scripts/install-run-rush.js test
  depends_on:
    - install

- name: test:ava
  image: node:gallium
  commands:
    - node common/scripts/install-run-rush.js test:ava
  depends_on:
    - install

- name: build
  image: node:gallium
  commands:
    - node common/scripts/install-run-rush.js build
  depends_on:
    - install

# TODO: can't push version and changelog back to the mainline branch, see this error:
# `fatal: could not read Username for 'https://github.com': terminal prompts disabled`
# Solutions:
# * https://docs.drone.io/pipeline/docker/syntax/cloning/auth/#machine-accounts
# * https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users

# - name: version
#   image: node:gallium
#   commands:
#     - npx standard-version
#     - git push --follow-tags origin main
#   when:
#     branch:
#       include:
#         - main

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel:
      from_secret: slack_channel
  when:
    status:
    - failure
    - success
  depends_on:
    - lint
    - lint:md
    - test
    - test:ava
    - build
