name: default

kind: pipeline
type: docker

# Create workspace at /drone/trshcmpctr instead of /drone/src (default).
workspace:
  base: /drone/trshcmpctr

steps:
  - name: install
    image: node:16.16.0
    environment:
      # Skip installing Cypress binary, already included in test:cypress image
      CYPRESS_INSTALL_BINARY: 0
    commands:
      - node common/scripts/install-run-rush.js install --purge

  - name: inject_secrets
    image: node:16.16.0
    environment:
      DISCORD_CLIENT_ID:
        from_secret: discord_client_id
      DISCORD_CLIENT_SECRET:
        from_secret: discord_client_secret
      DISCORD_GUILD_ID:
        from_secret: discord_guild_id
      DISCORD_SESSION_SECRET:
        from_secret: discord_session_secret
    commands:
      - (cd discord && ./client_config_ci.sh)

  - name: lint
    image: node:16.16.0
    commands:
      - node common/scripts/install-run-rush.js lint
    depends_on:
      - install
      - inject_secrets

  - name: lint:md
    image: node:16.16.0
    commands:
      - node common/scripts/install-run-rush.js lint:md
    depends_on:
      - install

  - name: test
    image: node:16.16.0
    commands:
      - node common/scripts/install-run-rush.js test
    depends_on:
      - install

  - name: test:cypress
    image: cypress/included:11.0.1
    commands:
      - node common/scripts/install-run-rush.js test:cypress --verbose
    depends_on:
      - install
      - inject_secrets

  - name: build
    image: node:16.16.0
    commands:
      - node common/scripts/install-run-rush.js build
    depends_on:
      - install

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel:
        from_secret: slack_channel
    when:
      status:
        - failure
        - success
    depends_on:
      - lint
      - lint:md
      - test
      - test:cypress
      - build
