name: default

kind: pipeline
type: docker

steps:
- name: install
  image: node:erbium
  commands:
    - npm ci

- name: lint
  image: node:erbium
  commands:
    - npm run lint

- name: type-check
  image: node:erbium
  commands:
    - npm run type-check

- name: test
  image: node:erbium
  commands:
    - npm run test

- name: build
  image: node:erbium
  commands:
    - npm run build:production

# TODO: can't push version and changelog back to the mainline branch, see this error:
# `fatal: could not read Username for 'https://github.com': terminal prompts disabled`
# Solutions:
# * https://docs.drone.io/pipeline/docker/syntax/cloning/auth/#machine-accounts
# * https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users

# - name: version
#   image: node:erbium
#   commands:
#     - npx standard-version
#     - git push --follow-tags origin main
#   when:
#     branch:
#       include:
#         - main

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel:
      from_secret: slack_channel
  when:
    status:
    - failure
    - success
