name: GitHub Actions CI (Branch)

on:
  push:
    branches-ignore:
    - main
    - 'stage/**'
  workflow_call:

jobs:
  install:
    uses: ./.github/workflows/install.yml

  build:
    needs:
    - install
    uses: ./.github/workflows/build.yml

  lint:
    needs: 
    - install
    - build
    uses: ./.github/workflows/lint.yml

  unit-test:
    needs:
    - install
    - build
    uses: ./.github/workflows/unit-test.yml

  e2e-test:
    needs:
    - install
    - build
    uses: ./.github/workflows/e2e-test.yml
    # Need repository-level secrets
    secrets: inherit
