name: GitHub Actions CI (Branch)

on:
  pull_request:
    branches: [ "main" ]
  # TODO: FIXME: how to trigger on push to all branches?
  push:
    branches: [ "dev-pipeline" ]

# TODO: what version of node are we getting and why? rush.json? actions default?

# TODO: what jobs should be broken out into reusiable workflows?
# https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

jobs:
  install:
    uses: ./.github/workflows/install.yml

  build:
    needs: install
    uses: ./.github/workflows/build.yml

  lint:
    needs: [install, build]
    uses: ./.github/workflows/lint.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  unit-test:
    needs: [install, build]
    uses: ./.github/workflows/unit-test.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  e2e-test:
    needs: [install, build]
    uses: ./.github/workflows/e2e-test.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  # TODO: FIXME: deploy should only run on merge to main or push to stage/** branches
  deploy:
    needs: [install, build, unit-test, e2e-test, lint]
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit
