name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Restore Build Cache
      id: restore-build-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/Cypress
          common/temp
          */.rush/temp
          */node_modules
          */dist
        key: ${{ runner.os }}-build-${{ hashFiles('common/config/rush/repo-state.json') }}
        # Only need a cache hit or miss,
        # cached dependencies aren't used until following jobs
        lookup-only: true

    - name: Restore Dependencies From Cache
      id: restore-cache
      uses: actions/cache/restore@v4
      if: steps.restore-build-cache.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.cache/Cypress
          common/temp
          */.rush/temp
          */node_modules
        key: ${{ runner.os }}-${{ hashFiles('common/config/rush/repo-state.json') }}
        fail-on-cache-miss: true

    - name: Build
      if: steps.restore-build-cache.outputs.cache-hit != 'true'
      run: node common/scripts/install-run-rush.js build

    - name: Save Build Cache
      id: save-cache
      uses: actions/cache/save@v4
      if: steps.restore-build-cache.outputs.cache-hit != 'true'
      with:
        path: |
          ~/.cache/Cypress
          common/temp
          */.rush/temp
          */node_modules
          */dist
        key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}
