name: E2E Tests

on:
  workflow_call:

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Restore Build Cache
      id: restore-build-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/Cypress
          common/temp
          */.rush/temp
          */node_modules
          */dist
        key: ${{ runner.os }}-build-${{ hashFiles('common/config/rush/repo-state.json') }}
        fail-on-cache-miss: true

    - name: Configure Discord Secrets
      run: (cd discord && ./client_config_ci.sh)
      env:
        # Repository-level secrets
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
        DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        DISCORD_REDIRECT_URI: ${{ secrets.DISCORD_REDIRECT_URI }}
        DISCORD_SESSION_SECRET: ${{ secrets.DISCORD_SESSION_SECRET }}

    - name: E2E Tests
      run: node common/scripts/install-run-rush.js test:cypress --verbose
