name: GitHub Actions CI (Main)

on:
  push:
    branches:
    - main

jobs:
  main-install:
    uses: ./.github/workflows/install.yml

  main-build:
    needs:
    - main-install
    uses: ./.github/workflows/build.yml

  main-lint:
    needs:
    - main-install
    - main-build
    uses: ./.github/workflows/lint.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  main-unit-test:
    needs:
    - main-install
    - main-build
    uses: ./.github/workflows/unit-test.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  main-e2e-test:
    needs:
    - main-install
    - main-build
    uses: ./.github/workflows/e2e-test.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  main-deploy:
    needs:
    - main-install
    - main-build
    - main-unit-test
    - main-e2e-test
    - main-lint
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit
