name: GitHub Actions CI (Main)

on:
  push:
    branches:
    - main

jobs:
  main-branch:
    uses: ./.github/workflows/branch.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  main-deploy:
    needs:
    - main-branch
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit
