name: GitHub Actions CI (Staging Deploy)

on:
  push:
    branches:
    - 'stage/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://www-stage.trshcmpctr.com
    steps:
    - uses: actions/checkout@v3
    - run: node common/scripts/install-run-rush.js install
    - uses: docker://node:18.16.1
    - run: node common/scripts/install-run-rush.js build --to=@trshcmpctr/deploy
    - run: (cd deploy && ./client_config_ci.sh)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    - run: (cd deploy && npm start ${{ vars.ENVIRONMENT }})
