name: GitHub Actions CI (Staging Deploy)

on:
  push:
    branches:
    - 'stage/**'

jobs:
  stage-branch:
    uses: ./.github/workflows/branch.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit

  stage-deploy:
    needs:
    - stage-branch
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    secrets: inherit
