name: Unit Tests

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
    - uses: actions/checkout@v4

    - name: Restore Build Cache
      id: restore-build-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/Cypress
          common/temp
          */.rush/temp
          */node_modules
          */dist
        key: ${{ runner.os }}-build-${{ hashFiles('common/config/rush/repo-state.json') }}
        fail-on-cache-miss: true

    - name: Configure Discord Secrets
      run: (cd discord && ./client_config_ci.sh)
      env:
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
        DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        DISCORD_SESSION_SECRET: ${{ secrets.DISCORD_SESSION_SECRET }}
        DISCORD_REDIRECT_URI: ${{ secrets.DISCORD_REDIRECT_URI }}

    - name: Configure Deploy Secrets
      run: (cd deploy && ./client_config_ci.sh)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}

    - name: Unit Tests
      run: node common/scripts/install-run-rush.js test
